### ISSUE TITLE
google-play-api consistency

### ISSUE THREAD

**Issue by Hemanthkumar16** [facundoolano/google-play-api#5]
i am using facundoolano/google-play-api (@facundoolano) for fetching app details from google play store in real time but performance is not upto mark. when access google play store using this, it throws an error for apps like amazon, ebay. it does not provide any consistency in getting details of google apps. so please help me to fetch app details from google play store in real time using google-play-api with consistency.

**Comment by facundoolano** [comment]
I'm not sure how to help you. If you are seeing errors please explain what the errors are and how to reproduce them.

About performance you can't really expect it out of the box, this is merely a REST wrapper around a scrapper; when you fetch a page you're actually making one or multiple requests to Google Play and parsing the results. If you want performance you'll probably have to add caching layers on top of the API or just dump the data to a database instead of fetching it in real time.

**Comment by Hemanthkumar16** [comment]
I have to know is there any limits to send request to google play store
using google play api bcoz my service is actually running but when I send
request to google the service is not responding i.e. i haven't got any
output from google play store after 70 to 80 successful request. Please let
me know ASAP thanks in advance

**Comment by facundoolano** [comment]
Yes, google will block you if you request too frequently. You can avoid this by tuning the [throttle](https://github.com/facundoolano/google-play-scraper#throttling) parameter of the scraper.

**Comment by Hemanthkumar16** [comment]
Okay i understand but its for scrapper right i am using google play api. Is
there any limit for no. Of request to play store via play api. If so, can
you specify it in number's ?

**Comment by facundoolano** [comment]
It's the same, the api uses the scraper to make the calls. There's no way to know the limits Google Play imposes, other than test them yourself. If you want to avoid hitting the Google Play limits, modify the api code to use the scraper option I mentioned.

**Comment by Hemanthkumar16** [comment]
Got it. ill try it. Thanks
