### ISSUE TITLE
{"message":"Unexpected token , in JSON at position 6038"}

### ISSUE THREAD

**Issue by zitanix** [facundoolano/google-play-api#51]
hello

what is this error for?

{"message":"Unexpected token , in JSON at position 6038"}

**Comment by lau1944** [comment]
me at position 143

**Comment by icarcal** [comment]
@zitanix @lau1944 this problem is from the [google-play-scraper](https://github.com/facundoolano/google-play-scraper/) package.

[This PR](https://github.com/facundoolano/google-play-scraper/pull/430) fix the issue and if you need this ASAP, you can try [this](https://github.com/facundoolano/google-play-scraper/issues/429#issuecomment-680621617) quick fix
