### ISSUE TITLE
is this api working 

### ISSUE THREAD

**Issue by AbhishekOnedigital** [facundoolano/google-play-api#71]
I have downloaded the latest version but it is giving an error 

i am calling /api/apps/{bundleid}

![image](https://user-images.githubusercontent.com/17587331/172851674-059c1050-a50e-449e-b501-d0884d4139e7.png)

**Comment by srikanthlogic** [comment]
Google recently changed the layout and the scraper is breaking. There are fixes being tried out at https://github.com/facundoolano/google-play-scraper/ , will update this once something gets merged upstream.

**Comment by AbhishekOnedigital** [comment]
Thanks @srikanthlogic

**Comment by joe21244966** [comment]
Same problem.wait for update.Thanks.

**Comment by srikanthlogic** [comment]
@facundoolano I suggest we put an note on README *and* a dev branch here that points to https://github.com/facundoolano/google-play-scraper.git in dependencies, so that people can always attempt to use `dev` branch if they found `master` not working. -- Submitted #76, might need to add a note on readme.
